import type { CurrentUserContext } from "@/src/application/local-user-context"; import type { CollectionRepository } from "@/src/application/ports/collection-repository"; import type { ContentRepository } from "@/src/application/ports/content-repository"; import type { LibraryEntryRepository } from "@/src/application/ports/library-entry-repository"; import { Collection } from "@/src/domain/collection/collection"; import { EntityId } from "@/src/domain/shared/entity-id";
export type CollectionListItem = { id: string; name: string; entryCount: number }; export type CollectionDetail = CollectionListItem & { entries: { id: string; title: string; mediaType: string }[] };
const valid = (value: string, code: string) => { try { EntityId.create(value); } catch { throw new Error(code); } };
export class CreateCollectionService { constructor(private readonly collections: CollectionRepository, private readonly user: CurrentUserContext) {} async create(name: string) { if (typeof name !== "string" || !name.trim()) throw new Error("INVALID_COLLECTION_NAME"); const userId = await this.user.getCurrentUserId(); if (await this.collections.existsByOwnerAndName(userId, name.trim())) throw new Error("DUPLICATE_COLLECTION_NAME"); const collection = Collection.create(EntityId.create(crypto.randomUUID()), EntityId.create(userId), name); await this.collections.save(collection); return { id: collection.id.value, name: collection.name, entryCount: 0 }; } }
export class GetCollectionsService { constructor(private readonly collections: CollectionRepository, private readonly entries: LibraryEntryRepository, private readonly user: CurrentUserContext) {} async list() { const userId = await this.user.getCurrentUserId(); return Promise.all((await this.collections.listByOwnerId(userId)).map(async (collection) => ({ id: collection.id.value, name: collection.name, entryCount: (await this.collections.entryIds(collection.id.value)).length }))); } async forEntry(entryId: string) { valid(entryId, "INVALID_ENTRY_ID"); const entry = await this.entries.findById(entryId); if (!entry || entry.properties.userId.value !== await this.user.getCurrentUserId()) return null; return Promise.all((await this.collections.listByEntryId(entryId)).filter((collection) => collection.userId.value === entry.properties.userId.value).map(async (collection) => ({ id: collection.id.value, name: collection.name, entryCount: (await this.collections.entryIds(collection.id.value)).length }))); } }
export class GetCollectionService { constructor(private readonly collections: CollectionRepository, private readonly entries: LibraryEntryRepository, private readonly contents: ContentRepository, private readonly user: CurrentUserContext) {} async get(id: string): Promise<CollectionDetail | null> { valid(id, "INVALID_COLLECTION_ID"); const collection = await owned(this.collections, this.user, id); if (!collection) return null; const entries = await Promise.all((await this.collections.entryIds(id)).map(async (entryId) => { const entry = await this.entries.findById(entryId); if (!entry || entry.properties.userId.value !== collection.userId.value) return null; const content = await this.contents.findById(entry.properties.contentId.value); return content ? { id: entryId, title: content.properties.title, mediaType: content.properties.mediaType } : null; })); const items = entries.filter((entry): entry is NonNullable<typeof entry> => entry !== null); return { id: collection.id.value, name: collection.name, entryCount: items.length, entries: items }; } }
export class AddEntryToCollectionService { constructor(private readonly collections: CollectionRepository, private readonly entries: LibraryEntryRepository, private readonly user: CurrentUserContext) {} async add(collectionId: string, entryId: string) { valid(collectionId, "INVALID_COLLECTION_ID"); valid(entryId, "INVALID_ENTRY_ID"); const collection = await owned(this.collections, this.user, collectionId); const entry = await this.entries.findById(entryId); if (!collection || !entry || entry.properties.userId.value !== collection.userId.value) return false; if (await this.collections.hasEntry(collectionId, entryId)) throw new Error("DUPLICATE_MEMBERSHIP"); await this.collections.addEntry(collectionId, entryId); return true; } }
export class RemoveEntryFromCollectionService { constructor(private readonly collections: CollectionRepository, private readonly user: CurrentUserContext) {} async remove(collectionId: string, entryId: string) { valid(collectionId, "INVALID_COLLECTION_ID"); valid(entryId, "INVALID_ENTRY_ID"); if (!await owned(this.collections, this.user, collectionId)) return false; if (!await this.collections.hasEntry(collectionId, entryId)) return null; await this.collections.removeEntry(collectionId, entryId); return true; } }
export class DeleteCollectionService { constructor(private readonly collections: CollectionRepository, private readonly user: CurrentUserContext) {} async delete(id: string) { valid(id, "INVALID_COLLECTION_ID"); if (!await owned(this.collections, this.user, id)) return false; await this.collections.delete(id); return true; } }
async function owned(repo: CollectionRepository, user: CurrentUserContext, id: string) { const collection = await repo.findById(id); return collection && collection.userId.value === await user.getCurrentUserId() ? collection : null; }
